apiVersion: v2
appVersion: 2.11.2
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:74f2cb86ebc9f0bc589d861c14ba533685e726d26d27b2ca2bdc2c06d46bfea9
type: application
version: 2.11.2
